server:
  port: 8081

spring:
  main:
    allow-bean-definition-overriding: true  # ✅ Allows overriding duplicate beans

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/myrealm  # ✅ Ensure this is correct

keycloak:
  server-url: http://localhost:8080  # ✅ Remove `/auth` if using Keycloak 17+
  realm: myrealm
  client-id: admin-cli # ✅ Use admin-cli for admin tasks, OR ensure "my-app" is confidential
  grant-type: password
#  client-secret: qvjBEjRkFDESdNUWc5LgGhaPZpSS7JG1
  username: admin321
  password: admin321
